### ISSUE TITLE
关于预训练模型的问题

### ISSUE THREAD

**Issue by Iven-Wang** [redreamality/RERE-relation-extraction#1]
您好，我对您的工作非常感兴趣，这里有一个问题希望请教一下：

我在代码中看到，RERE 使用的是 BERT-uncased，请问在 table 3 中复现的 casrel 和  tplinker 也是使用的 BERT-uncased 吗？casrel 的复现结果与其在原文中使用 BERT-cased 得到的结果完全一致吗？

**Comment by redreamality** [comment]
复现使用的设置和原文保持一致。CasRel用的是bojone[开源的版本](https://github.com/bojone/bert4keras/blob/master/examples/task_relation_extraction.py)。


-------------------------------------------
Translation

**Question**


Hello, I am very interested in your work, here is a question I would like to ask:

I see in the code that RERE uses BERT-uncased. Do the casrel and tplinker reproduced in table 3 also use BERT-uncased? Are the reproduced results of casrel exactly the same as those obtained with BERT-cased in the original text? 

**Answer**

The settings used for reproduction are consistent with the original. CasRel uses bojone‘s [open source version](https://github.com/bojone/bert4keras/blob/master/examples/task_relation_extraction.py).
