### ISSUE TITLE
模型架构问题

### ISSUE THREAD

**Issue by Hou-jing** [redreamality/RERE-relation-extraction#2]
您好，我在看代码的时候，发现关系分类和实体抽取两个子任务是分开进行的，但是在论文中，实体抽取是以关系关系模型的结果为基础构建输入，请问，代码和论文是否是有区别的呢？
另外，在评测准确率时，是对关系抽取和实体抽取分开评测吗？在论文中的评测结果展示的是是否为实体抽取模型的评测结果呢？
麻烦解答一下，谢谢~

**Comment by redreamality** [comment]
分开训练，但是合起来预测。

对于测试样本，先用Relation Classification， 其结果传入后续Entity Extractor。 

评测结果是整个模型结果。

-------------------------------

In case there are international readers, I google translate the QA.

**Question**
Hello, when I was looking at the code, I found that the two sub-tasks of relationship classification and entity extraction are carried out separately, but in the paper, entity extraction is based on the results of the relationship model. Is there a difference? In addition, when evaluating the accuracy, is the relationship extraction and entity extraction evaluated separately? Do the evaluation results in the paper show the evaluation results of the entity extraction model? Please answer, thank you~


**Answer**

Train separately, but predict together.

For test samples, use Relation Classification first, and pass the results to the subsequent Entity Extractor.

The evaluation result is for the whole model.
